version: "3.7"

services:
  database:
    image: mysql:latest
    container_name: database_test
    restart: always
    environment:
      MYSQL_DATABASE: database_test
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
